name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu-2004-gcc:
    strategy:
      matrix:
        mruby-version:
          - 2.1.2
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1.59.1
        with:
          ruby-version: '2.7'
      - name: Build and test
        env:
          CC: gcc
          CXX: g++
          MRUBY_VERSION: ${{ matrix.mruby-version }}
        run: rake test
